config/routes.rb
Rails.application.routes.draw do

  get 'home/get_search_result'

  get 'products/index'

  get 'products/edit'

  get 'products/create'

  get 'products/new'

  get 'products/destroy'

  get 'products/show'

  get 'products/update'

  devise_for :users

  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products, through: :product_in_carts
  has_many :product_in_carts
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :carts, through: :product_in_carts
  has_many :product_in_carts


  def self.search(condition)
    self
        .where('name LIKE ? ', "%#{condition}%")

  end
end

app/models/product_in_cart.rb
class ProductInCart < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  validate :quantity
  validate :price
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :carts
  belongs_to :role

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.all
  end

  def get_search_result
    @result = Product.where('name LIKE ? ', "%#{params[:condition]}%")
    redirect_to products_index_url( :result => @result)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all
    @products = params[:result]

  end

  def edit
  end

  def create
  end

  def new
  end

  def destroy
  end

  def show
  end

  def update
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.all
    @products = Product.all
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end



end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_banner.html.erb
<div class="banner">
  <div class="w3l_banner_nav_left">
    <nav class="navbar nav_bottom">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header nav_2">
        <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
        <ul class="nav navbar-nav nav_1">
          <% @categories.each do |c| %>
              <li><a href="products.html"><%= c.name %></a></li>

          <% end %>

          <li><a href="products.html">Branded Foods</a></li>
          <li><a href="household.html">Households</a></li>
          <li class="dropdown mega-dropdown active">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Veggies & Fruits<span class="caret"></span></a>
            <div class="dropdown-menu mega-dropdown-menu w3ls_vegetables_menu">
              <div class="w3ls_vegetables">
                <ul>
                  <li><a href="vegetables.html">Vegetables</a></li>
                  <li><a href="vegetables.html">Fruits</a></li>
                </ul>
              </div>
            </div>
          </li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  </div>
  <div class="w3l_banner_nav_right">
    <section class="slider">
      <div class="flexslider">
        <ul class="slides">
          <li>
            <div class="w3l_banner_nav_right_banner">
              <!--<h3>Make your <span>food</span> with Spicy.</h3>
              <div class="more">
                <a href="products.html" class="button&#45;&#45;saqui button&#45;&#45;round-l button&#45;&#45;text-thick" data-text="Shop now">Shop now</a>
              </div>-->
            </div>
          </li>
          <li>
            <div class="w3l_banner_nav_right_banner1">
              <!--<h3>Make your <span>food</span> with Spicy.</h3>
              <div class="more">
                <a href="products.html" class="button&#45;&#45;saqui button&#45;&#45;round-l button&#45;&#45;text-thick" data-text="Shop now">Shop now</a>
              </div>-->
            </div>
          </li>
          <li>
            <div class="w3l_banner_nav_right_banner2">
             <!-- <h3>upto <i>50%</i> off.</h3>
              <div class="more">
                <a href="products.html" class="button&#45;&#45;saqui button&#45;&#45;round-l button&#45;&#45;text-thick" data-text="Shop now">Shop now</a>
              </div>-->
            </div>
          </li>
        </ul>
      </div>
    </section>
    <!-- flexSlider -->

    <script type="text/javascript">
        $(window).load(function(){
            $('.flexslider').flexslider({
                animation: "slide",
                start: function(slider){
                    $('body').removeClass('loading');
                }
            });
        });
    </script>
    <!-- //flexSlider -->
  </div>
  <div class="clearfix"></div>
</div>

app/views/layouts/application.html.erb
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
  <title>CosmeticS Store</title>
  <!-- for-mobile-apps -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="Cosmetic store" />
  <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
  function hideURLbar(){ window.scrollTo(0,1); } </script>
  <!-- //for-mobile-apps -->
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'bootstrap' %>
  <%= stylesheet_link_tag    'style' %>
  <%= stylesheet_link_tag    'font-awesome' %>
  <%= stylesheet_link_tag    'flexslider' %>

  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'move-top' %>
  <%= javascript_include_tag 'easing' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'jquery.flexslider' %>

  <script type="text/javascript">
      jQuery(document).ready(function($) {
          $(".scroll").click(function(event){
              event.preventDefault();
              $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
          });
      });
  </script>
  <!-- start-smoth-scrolling -->
</head>

<body>
<!-- header -->
<div class="agileits_header">
  <div class="w3l_offers">
    <a href="products.html">Today's special Offers !</a>
  </div>
  <div class="w3l_search">
    <form action="<%= home_get_search_result_path %>" method="get">
      <input type="text" name="condition" value="Search a product..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search a product...';}" required="">
      <input type="submit" value=" ">
    </form>
  </div>
  <div class="product_list_header">
    <form action="#" method="post" class="last">
      <fieldset>
        <input type="hidden" name="cmd" value="_cart" />
        <input type="hidden" name="display" value="1" />
        <input type="submit" name="submit" value="View your cart" class="button" />
      </fieldset>
    </form>
  </div>
  <div class="w3l_header_right">
    <ul>
      <li class="dropdown profile_details_drop">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i><span class="caret"></span></a>
        <div class="mega-dropdown-menu">
          <div class="w3ls_vegetables">
            <ul class="dropdown-menu drp-mnu">
              <% if user_signed_in? %>
                  <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                  </li>
              <% else %>
                  <li><%= link_to "Log in", new_user_session_path %> </li>
                  <li><%= link_to "Sign up",  new_user_registration_path %> </li>
              <% end %>


            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
  <div class="w3l_header_right1">
    <h2><a href="mail.html">Contact Us</a></h2>
  </div>
  <div class="clearfix"> </div>
</div>
<!-- script-for sticky-nav -->
<script>
    $(document).ready(function() {
        var navoffeset=$(".agileits_header").offset().top;
        $(window).scroll(function(){
            var scrollpos=$(window).scrollTop();
            if(scrollpos >=navoffeset){
                $(".agileits_header").addClass("fixed");
            }else{
                $(".agileits_header").removeClass("fixed");
            }
        });

    });
</script>
<!-- //script-for sticky-nav -->
<div class="logo_products">
  <div class="container">
    <div class="w3ls_logo_products_left">
      <h1><a href="index.html"><span>CosmeticS</span> Store</a></h1>
    </div>
    <div class="w3ls_logo_products_left1">
      <ul class="special_items">
        <li><a href="events.html">Events</a><i>/</i></li>
        <li><a href="about.html">About Us</a><i>/</i></li>
        <li><a href="products.html">Best Deals</a><i>/</i></li>
        <li><a href="services.html">Services</a></li>
      </ul>
    </div>
    <div class="w3ls_logo_products_left1">
      <ul class="phone_email">
        <li><i class="fa fa-phone" aria-hidden="true"></i>(+0123) 234 567</li>
        <li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailto:store@cosmetics.com">store@cosmetics.com</a></li>
      </ul>
    </div>
    <div class="clearfix"> </div>
  </div>
</div>
<!-- //header -->
<!-- banner -->

<!-- banner -->

<%= yield %>



<!-- footer -->
<div class="footer">
  <div class="container">

    <div class="wthree_footer_copy">
      <p>© 2016 CosmeticS Store. All rights reserved </p>
    </div>
  </div>
</div>
<!-- //footer -->
<!-- Bootstrap Core JavaScript -->
<%= javascript_include_tag 'bootstrap.min' %>

<script>
    $(document).ready(function(){
        $(".dropdown").hover(
            function() {
                $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
                $(this).toggleClass('open');
            },
            function() {
                $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
                $(this).toggleClass('open');
            }
        );
    });
</script>
<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function() {
      /*
       var defaults = {
       containerID: 'toTop', // fading element id
       containerHoverID: 'toTopHover', // fading element hover id
       scrollSpeed: 1200,
       easingType: 'linear'
       };
       */

        $().UItoTop({ easingType: 'easeOutQuart' });

    });
</script>
<!-- //here ends scrolling icon -->
<%= javascript_include_tag 'minicart.min' %>

<script>
    // Mini Cart
    paypal.minicart.render({
        action: '#'
    });

    if (~window.location.search.indexOf('reset=true')) {
        paypal.minicart.reset();
    }
</script>



</body>
</html>